name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js Application
        run: yarn build

      - name: Compress Build Directory
        run: zip -r build.zip .next public package.json yarn.lock

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: build.zip
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-zip

      - name: Deploy Build ZIP via Kudu ZipDeploy
        run: |
          curl -X POST -u "$DEPLOYMENT_USERNAME:$DEPLOYMENT_PASSWORD" \
          --data-binary @build.zip \
          "https://$AZURE_APP_NAME.scm.canadacentral-01.azurewebsites.net/api/deployments"
        env:
          AZURE_APP_NAME: "rentalsite-gxenhwfaaxgth5cw"  # Replace with your App Service name
          DEPLOYMENT_USERNAME: ${{ secrets.AZURE_DEPLOYMENT_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.AZURE_DEPLOYMENT_PASSWORD }}

