name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js Application
        run: yarn build

      - name: Compress Build Directory
        run: zip -r build.zip .next public package.json yarn.lock

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: build.zip
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-zip

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: rentaldemo  # Replace with your Azure app name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Your publish profile secret
          package: build.zip
