name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build Next.js Application
        run: yarn build

      - name: Compress Build Directory
        run: zip -r build.zip .next public package.json yarn.lock

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-zip
          path: build.zip
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-zip

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Verify FTP Connection
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" ftps://$AZURE_FTP_HOST -e "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ftp:passive-mode true;
          ls;
          bye"
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          AZURE_FTP_HOST: ${{ secrets.AZURE_FTP_HOST }}

      - name: Upload Build ZIP to Azure App Service
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" ftps://$AZURE_FTP_HOST -e "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ftp:passive-mode true;
          cd site/wwwroot;
          put build.zip;
          bye"
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          AZURE_FTP_HOST: ${{ secrets.AZURE_FTP_HOST }}

      - name: Trigger Kudu API for ZipDeploy (Automatic Unzip)
        run: |
          curl -X POST -u "$DEPLOYMENT_USERNAME:$DEPLOYMENT_PASSWORD" \
          "https://rentalsite-gxenhwfaaxgth5cw.scm.canadacentral-01.azurewebsites.net/api/zipdeploy"
        env:
          DEPLOYMENT_USERNAME: ${{ secrets.FTP_USERNAME }}
          DEPLOYMENT_PASSWORD: ${{ secrets.FTP_PASSWORD }}
